adventure_crew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('adventurers/', views.adventurers_index, name='index'),
    path('adventurers/<name>/', views.adventurers_detail, name='detail'),
    path('adventurers/<int:adventurer_id>/<name>/add_journey', views.add_journey, name='add_journey'),
    path('adventurers/<int:adventurer_id>/delete', views.adventurers_delete, name='adventurers_delete'),
    path('adventurers/<int:adventurer_id>/<name>/edit', views.adventurers_edit, name="adventurers_edit"),
    path('adventurers/<int:adventurer_id>/<name>/assoc_toy/<int:enemy_id>/', views.assoc_enemy, name='assoc_enemy'),
    path('adventurers/<int:adventurer_id>/<name>/deassoc_toy/<int:enemy_id>/', views.deassoc_enemy, name='deassoc_enemy'),
    path('adventurers/<int:adventurer_id>/<name>/assoc_gear/<int:gear_id>/', views.assoc_gear, name='assoc_gear')
]

main_app/models.py
from django.db import models

# Create your models here.
class Enemy(models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    treasure = models.IntegerField()
    health = models.IntegerField()

    def __str__(self):
        return self.name

class Gear(models.Model):
    name = models.CharField(max_length=100)
    attack = models.IntegerField('attack power')
    armor = models.IntegerField('armor bonus')
    heal = models.IntegerField('heal bonus')
    cost = models.IntegerField()

    def __str__(self):
        return self.name


class Adventurer(models.Model):
    name = models.CharField(max_length=100, unique=True)
    style = models.CharField('combat style', max_length=100)
    weapon = models.CharField('perferred weapon', max_length=100)
    health = models.IntegerField()
    wealth = models.IntegerField()

    enemys = models.ManyToManyField(Enemy)
    gears = models.ManyToManyField(Gear)

    def __str__(self):
        return self.name
    
    def change_wealth(self, amount):
        self.wealth = self.wealth + amount
        self.save()

class Journey(models.Model):
    goal = models.CharField(max_length=100)
    challenge = models.CharField(max_length=100)
    reward = models.CharField(max_length=100)

    adventurer = models.ForeignKey(Adventurer, on_delete=models.CASCADE)

    def __str__(self):
        return f"A Journey for {self.goal}"

main_app/forms.py
from django.forms import ModelForm
from .models import Journey, Adventurer

class AdventurerForm(ModelForm):
    class Meta:
        model = Adventurer
        fields = ['name', 'style', 'weapon', 'health', 'wealth']

class JourneyForm(ModelForm):
    class Meta:
        model = Journey
        fields = ['goal', 'challenge', 'reward']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Adventurer, Enemy, Gear
from .forms import JourneyForm, AdventurerForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def adventurers_index(request):
    if request.method == 'POST':
        adventurer_form = AdventurerForm(request.POST)
        if adventurer_form.is_valid():
            adventurer_form.save()
            return redirect('index')
    adventurers = Adventurer.objects.all()
    adventurer_form = AdventurerForm()
    context = {'adventurers': adventurers, 'adventurer_form': adventurer_form}
    return render(request, 'adventurers/index.html', context)

def adventurers_detail(request, name):
    adventurer = Adventurer.objects.get(name=name)
    future_enemies = Enemy.objects.exclude(id__in = adventurer.enemys.all().values_list('id'))
    future_gear = Gear.objects.exclude(id__in = adventurer.gears.all().values_list('id'))
    journey_form = JourneyForm()
    return render(request, 'adventurers/detail.html', { 
        'adventurer': adventurer, 
        'journey_form': journey_form,
        'enemys': future_enemies,
        'gears': future_gear
    })

def add_journey(request, adventurer_id, name):
    form = JourneyForm(request.POST)
    if form.is_valid():
        new_journey = form.save(commit=False)
        new_journey.adventurer_id = adventurer_id
        new_journey.save()
    return redirect('detail', name=name)

def adventurers_delete(request, adventurer_id):
    Adventurer.objects.get(id=adventurer_id).delete()
    return redirect('index')

def adventurers_edit(request, adventurer_id, name):
    adventurer = Adventurer.objects.get(id=adventurer_id)
    if request.method == 'POST':
        adventurer_form = AdventurerForm(request.POST, instance=adventurer)
        if adventurer_form.is_valid():
            adventurer_form.save()
            return redirect('detail', name=name)
    else:
        adventurer_form = AdventurerForm(instance=adventurer)
    context = {'adventurer': adventurer, 'adventurer_form': adventurer_form}
    return render(request, 'adventurers/edit.html', context)

def assoc_enemy(request, adventurer_id, name, enemy_id):
    Adventurer.objects.get(id=adventurer_id).enemys.add(enemy_id)
    return redirect('detail', name=name)

def deassoc_enemy(request, adventurer_id, name, enemy_id):
    Adventurer.objects.get(id=adventurer_id).enemys.remove(enemy_id)
    return redirect('detail', name=name)

def assoc_gear(request, adventurer_id, name, gear_id):
    adventurer = Adventurer.objects.get(id=adventurer_id)
    gear = Gear.objects.get(id=gear_id)
    adventurer.change_wealth(-gear.cost)
    adventurer.gears.add(gear_id)
    return redirect('detail', name=name)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>About the Adventure Crew</h1>
    <h4>The place to come for adventurers.</h4><br><br>
    <h6>This is a demonstration site using the following technologies:</h6>
    <ul>
        <li>Django framework</li>
        <li>Postgres SQL database</li>
        <li>Materialize library</li>
    </ul>
{% endblock %}

main_app/templates/adventurers/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Adventurer Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">

            <div class="card-content">
                <span class="card-title">{{ adventurer.name }}</span>
                <p>Fighting style: {{ adventurer.style }}</p>
                <p>Preferred weapon: {{ adventurer.weapon }}</p>
                <p>Health: {{ adventurer.health }}</p>
                {% if adventurer.wealth > 1000 %}
                    <p>Wealth: This adventurer is rich. They have ₤{{ adventurer.wealth }}</p>
                {% else %}
                    <p>Wealth: This adventurer is poor. They have ₤{{ adventurer.wealth }}</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'adventurers_delete' adventurer.id %}" class="btn red">Delete</a>
                <a href="{% url 'adventurers_edit' adventurer.id adventurer.name %}" class="btn blue">Edit</a>
            </div>
            
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_journey' adventurer.id adventurer.name %}" method="POST">
            {% csrf_token %}
            {{ journey_form.as_p }}
            <input type="submit" class="btn" value="Add Journey">
        </form>
        <table class="striped">
            <thead>
                <tr><th>Goal</th><th>Challenge</th><th>Reward</th></tr>
            </thead>
            <tbody>
                {% for journey in adventurer.journey_set.all %}
                <tr>
                    <td>{{journey.goal}}</td>
                    <td>{{journey.challenge}}</td>
                    <td>{{journey.reward}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ adventurer.name }}'s Enemies</h3>
            {% if adventurer.enemys.count %}
                {% for enemy in adventurer.enemys.all %}
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">The {{ enemy.species }} known as {{ enemy.name }}</span>
                        </div>
                        <div class="card-action">
                        <form action="{% url 'deassoc_enemy' adventurer.id adventurer.name enemy.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn red">Make Peace</button>
                        </form>
                    </div>
                    </div>
                {% endfor %}
            
            {% else %}
                <h5>What is an adventurer without any enemies? Go out and make some!</h5>
            {% endif %}
    </div>
    <div class="col s6">
        <h3>Potential Enemies</h3>
        {% if enemys.count %}
            {% for enemy in enemys.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">The {{ enemy.species }} known as {{ enemy.name }}</span>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'assoc_enemy' adventurer.id adventurer.name enemy.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn">Pick a Fight</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>{{ adventurer.name }} is feared by all enemies.</h5>
        {% endif %}
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ adventurer.name }}'s Gear</h3>
        {% if adventurer.gears.count %}
            {% for gear in adventurer.gears.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ gear.name }}</span>
                        <p>Attack power: {{ gear.attack }}</p>
                        <p>Armor bonus: {{ gear.armor }}</p>
                        <p>Heal bonus: {{ gear.heal }}</p>
                        <p>Cost: {{ gear.cost }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>An adventurer needs gear. You can't go into battle naked. You aren't Celtic.</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Gear Shop</h3>
        {% if gears.count %}
            {% for gear in gears.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ gear.name }}</span>
                        <p>Attack power: {{ gear.attack }}</p>
                        <p>Armor bonus: {{ gear.armor }}</p>
                        <p>Heal bonus: {{ gear.heal }}</p>
                        <p>Cost: {{ gear.cost }}</p>
                    </div>
                    <div class="card-action">
                    {% if gear.cost > adventurer.wealth %}
                        <h5>You can't afford it, honey.</h5>
                    {% else %}
                        <form action="{% url 'assoc_gear' adventurer.id adventurer.name gear.id %}" method="POST">
                            {% csrf_token %}
                            <button class="btn" type="submit">Buy It!</button>
                        </form>
                    {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h5>{{adventurer.name}} owns everything.</h5>
        {% endif %}
    </div>
</div>
{% endblock %}

main_app/templates/adventurers/edit.html
{% extends 'base.html' %}

{% block content %}

<h1>Edit {{ adventurer.name }}</h1>

<form action="{% url 'adventurers_edit' adventurer.id adventurer.name %}" method="POST">
    {% csrf_token %}
    {{ adventurer_form.as_p }}
    <input type="submit" class='btn' value="Update {{adventurer.name}}">
</form>

{% endblock %}

main_app/templates/adventurers/index.html
{% extends 'base.html' %}
{% block content %}

<div class="row">

    <h1>Adventurer List</h1>
    <div class="col s9">
        {% for adventurer in adventurers %}
        <div class="card">

            <a href="{% url 'detail' adventurer.name %}">
                <div class="card-content">
                    <span class="card-title">{{ adventurer.name }}</span>
                    <p>Fighting style: {{ adventurer.style }}</p>
                    <p>Preferred weapon: {{ adventurer.weapon }}</p>
                    <p>Health: {{ adventurer.health }}</p>
                    {% if adventurer.wealth > 1000 %}
                        <p>Wealth: Rich</p>
                    {% else %}
                        <p>Wealth: Poor</p>
                    {% endif %}
                </div>
            </a>

        </div>
    {% endfor %}
    </div>
    <div class="col s3">
        <form action="{% url 'index' %}" method="POST">
            {% csrf_token %}
            {{ adventurer_form.as_p }}
            <input type="submit" class="btn" value="Add Adventurer"/>
        </form>
    </div>
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Adventure Crew</title>
</head>
<body>
    <header class = "navbar-fixed">
        <nav>
            <div class = "nav-wrapper brown darken-3">
                <ul>
                    <li><a href="/" class= "left brand-logo">&nbsp;&nbsp;Adventure Crew</a></li>
                </ul>
                <ul class="right">
                    <li><a href="/about">About</a></li>
                    <li><a href="/adventurers">Meet all the Adventurers</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %} 
    </main>
    <footer class="page-footer brown darken-3">
        <div class= "right">All Rights Reserved &copy; 2020 Adventure Crew &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Adventure Crew</h1>
    <p>Any Adventurer, Anytime.</p>
{% endblock %}